name: oneplus_13t GKI Max Build
on:
  workflow_dispatch:
    inputs:
      CPU:
        description: "SoC平台分支"
        required: true
        default: 'sm8750'
      FEIL:
        description: "设备配置文件"
        required: true
        default: 'oneplus_13t'
      CPUD:
        description: "处理器代号"
        required: true
        default: 'sun'
      ANDROID_VERSION:
        description: "安卓版本"
        required: true
        default: 'android15'
      KERNEL_VERSION:
        description: "内核版本"
        required: true
        default: '6.6'
      KERNEL_NAME:
        description: "自定义内核名称"
        required: true
        default: '-Android15-8-@'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AK3_ACCESS_TOKEN: ${{ secrets.AK3_ACCESS_TOKEN }}
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"

    steps:
      - name: 最大化构建空间
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'

      - name: 配置Git身份
        run: |
          git config --global user.name "build"
          git config --global user.email "2106456897@qq.com"

      - name: 安装系统依赖
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y python3 git curl ccache bc build-essential flex bison libssl-dev libelf-dev

      - name: 安装repo工具
        run: |
          curl -s https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
          chmod a+x ~/repo
          sudo mv ~/repo /usr/local/bin/repo

      - name: 初始化代码仓库
        run: |
          mkdir -p kernel_workspace && cd kernel_workspace
          repo init -u https://github.com/MAXCUK/kernel_manifest.git \
            -b refs/heads/oneplus/${{ github.event.inputs.CPU }} \
            -m ${{ github.event.inputs.FEIL }}.xml \
            --depth=1
          repo sync -c -j$(nproc --all) --no-tags --force-sync
          
          # 清理保护导出文件
          find . -name "abi_gki_protected_exports_*" -delete

      - name: 部署KernelSU
        run: |
          cd kernel_workspace/kernel_platform
          curl -LSs "https://raw.githubusercontent.com/ShirkNeko/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-dev
          
          # 计算KSU版本
          cd KernelSU
          KSU_VERSION=$(expr $(git rev-list --count main) + 10606)
          echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
          sed -i "s/DKSU_VERSION=12800/DKSU_VERSION=${KSU_VERSION}/" kernel/Makefile

      - name: 应用SUSFS补丁
        run: |
          cd kernel_workspace
          # 强制清理旧补丁
          rm -rf susfs4ksu SukiSU_patch
          
          # 获取最新补丁
          git clone -q https://gitlab.com/simonpunk/susfs4ksu.git -b gki-${{ inputs.ANDROID_VERSION }}-${{ inputs.KERNEL_VERSION }}
          git clone -q https://github.com/ExmikoN/SukiSU_patch.git

          # 部署核心补丁
          cd kernel_platform
          cp -fv ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-*.patch common/
          cp -rfv ../susfs4ksu/kernel_patches/fs/* common/fs/
          cp -rfv ../susfs4ksu/kernel_patches/include/linux/* common/include/linux/

          # 应用LZ4K基础补丁
          cp -rfv ../SukiSU_patch/other/lz4k/include/linux/* common/include/linux/
          cp -rfv ../SukiSU_patch/other/lz4k/lib/* common/lib/
          cp -rfv ../SukiSU_patch/other/lz4k/crypto/* common/crypto/

          # 处理SUSFS补丁
          cd common
          sed -i 's/-32,12 +32,38/-32,11 +32,37/' 50_add_susfs_in_gki-*.patch
          sed -i '/#include <trace\/hooks\/fs.h>/d' 50_add_susfs_in_gki-*.patch
          patch -p1 < 50_add_susfs_in_gki-*.patch
          
          # 应用系统调用钩子
          cp ../../SukiSU_patch/hooks/syscall_hooks.patch .
          patch -p1 -F 3 < syscall_hooks.patch

      - name: 应用LZ4KD补丁
        run: |
          cd kernel_workspace/kernel_platform/common
          cp -v ../../SukiSU_patch/other/lz4k_patch/${{ inputs.KERNEL_VERSION }}/lz4kd.patch .
          patch -p1 -F 3 < lz4kd.patch

      - name: 内核配置增强
        run: |
          cd kernel_workspace/kernel_platform
          # 注入SUSFS配置
          cat <<EOT >> common/arch/arm64/configs/gki_defconfig
# KernelSU核心
CONFIG_KSU=y
CONFIG_KPM=y

# SUSFS功能配置
CONFIG_KSU_SUSFS=y
CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y
CONFIG_KSU_SUSFS_SUS_PATH=y
CONFIG_KSU_SUSFS_SUS_MOUNT=y
CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y
CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y

# 高级选项
CONFIG_KSU_SUSFS_SUS_SU=n
CONFIG_KSU_MANUAL_HOOK=y
CONFIG_KSU_SUSFS_SUS_KSTAT=y
CONFIG_KSU_SUSFS_TRY_UMOUNT=y
CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y
CONFIG_KSU_SUSFS_SPOOF_UNAME=y
CONFIG_KSU_SUSFS_ENABLE_LOG=y
CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y
CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y
CONFIG_KSU_SUSFS_OPEN_REDIRECT=y

# 压缩算法支持
CONFIG_CRYPTO_LZ4HC=y
CONFIG_CRYPTO_LZ4K=y
CONFIG_CRYPTO_LZ4KD=y
CONFIG_CRYPTO_842=y

# 系统优化
CONFIG_DTBO_VALIDATION=n
EOT

          # 绕过配置检查
          sed -i 's/check_defconfig//' common/build.config.gki
          git commit -am "[Automated] 应用完整内核配置"

      - name: 定制内核标识
        run: |
          cd kernel_workspace/kernel_platform
          sed -i 's|res="$res$(cat "$file")"|res="${{ inputs.KERNEL_NAME }}"|g' common/scripts/setlocalversion

      - name: 编译内核映像
        run: |
          cd kernel_workspace/kernel_platform
          export PATH=/usr/lib/ccache:$PATH
          tools/bazel run \
            --config=fast \
            --config=stamp \
            --lto=thin \
            //common:kernel_aarch64_dist -- --dist_dir=dist

      - name: 生成增强镜像
        run: |
          cd kernel_workspace/kernel_platform/dist
          cp -v Image Image_original
          curl -L https://github.com/ShirkNeko/SukiSU_KernelPatch_patch/releases/download/0.11-beta/patch_linux -o patch_linux
          chmod +x patch_linux
          ./patch_linux
          mv -v oImage Image_kpm
          mv -v Image_original Image

      - name: 准备刷机包
        run: |
          cd kernel_workspace/kernel_platform/dist
          git clone --depth=1 https://${{ env.AK3_ACCESS_TOKEN }}@github.com/MAXCUK/AnyKernel3-13t.git AnyKernel3-no_kpm
          git clone --depth=1 https://${{ env.AK3_ACCESS_TOKEN }}@github.com/MAXCUK/AnyKernel3-13t.git AnyKernel3-kpm
          
          # 清理git痕迹
          rm -rf AnyKernel3-{kpm,no_kpm}/.git
          
          # 部署内核镜像
          cp -v Image AnyKernel3-no_kpm/
          cp -v Image_kpm AnyKernel3-kpm/Image

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: oneplus_13t_${{ env.KSUVER }}
          path: |
            kernel_workspace/kernel_platform/dist/AnyKernel3-*/Image
            kernel_workspace/kernel_platform/dist/AnyKernel3-*/META-INF
