name: ace5pro gki
on:
  workflow_dispatch:
    inputs:
      CPU:
        description: "分支"
        required: true
        default: 'sm8750'
      FEIL:
        description: "配置文件"
        required: true
        default: 'oneplus_ace5_pro'
      CPUD:
        description: "处理器代号"
        required: true
        default: 'sun'
      ANDROID_VERSION:
        description: "内核安卓版本"
        required: true
        default: 'android15'
      KERNEL_VERSION:
        description: "内核版本"
        required: true
        default: '6.6'
      KERNEL_NAME:
        description: "修改内核名称"
        required: true
        default: '-android15-8-@'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'

      - name: Configure Git
        run: |
          git config --global user.name "build"
          git config --global user.email "2106456897@qq.com"

      - name: Setup SSH Environment
        run: |
          mkdir -p ~/.ssh
          # 严格处理密钥格式
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | sed '/^$/d' > ~/.ssh/id_ed25519
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/*
          
          # 生成增强SSH配置
          cat << EOF > ~/.ssh/config
          Host github.com
              HostName github.com
              User git
              IdentityFile ~/.ssh/id_ed25519
              IdentitiesOnly yes
              StrictHostKeyChecking no
              PubkeyAcceptedAlgorithms +ssh-ed25519
              HostkeyAlgorithms +ssh-ed25519
          EOF
          
          # 预加载GitHub指纹
          ssh-keyscan -t ed25519 github.com >> ~/.ssh/known_hosts
          
          # 连接测试
          echo "=== SSH连接测试 ==="
          ssh -T git@github.com || true
          echo "=== 仓库访问验证 ==="
          git ls-remote git@github.com:MAXCUK/sched.git HEAD

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y python3 git curl

      - name: Install repo tool
        run: |
          curl -fsSL https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
          chmod a+x ~/repo
          sudo mv ~/repo /usr/local/bin/repo

      - name: Initialize repo and sync
        run: |
          mkdir kernel_workspace && cd kernel_workspace
          repo init -u https://github.com/JiuGeFaCai/kernel_manifest.git \
            -b refs/heads/oneplus/${{ github.event.inputs.CPU }} \
            -m ${{ github.event.inputs.FEIL }}.xml \
            --depth=1
          repo sync -c -j$(nproc --all) --no-tags --no-clone-bundle
          rm -f kernel_platform/common/android/abi_gki_protected_exports_* 2>/dev/null || true

      - name: Set up SukiSU
        run: |
          cd kernel_workspace/kernel_platform
          curl -LSs "https://raw.githubusercontent.com/ShirkNeko/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-dev
          cd ./KernelSU
          KSU_VERSION=$(expr $(git rev-list --count main) "+" 10606)
          echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
          sed -i "s/DKSU_VERSION=12800/DKSU_VERSION=${KSU_VERSION}/" kernel/Makefile

      - name: Set up susfs
        run: |
          cd kernel_workspace
          git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}
          git clone https://github.com/ExmikoN/SukiSU_patch.git

          cd kernel_platform        
          cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch ./common/
          cp -r ../susfs4ksu/kernel_patches/fs/* ./common/fs/
          cp -r ../susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/
          cp -r ../SukiSU_patch/other/lz4k/include/linux/* ./common/include/linux
          cp -r ../SukiSU_patch/other/lz4k/lib/* ./common/lib
          cp -r ../SukiSU_patch/other/lz4k/crypto/* ./common/crypto

          cd ./common
          sed -i 's/-32,12 +32,38/-32,11 +32,37/g' 50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch
          patch -p1 < 50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch || true
          cp ../../SukiSU_patch/hooks/syscall_hooks.patch ./
          patch -p1 -F 3 < syscall_hooks.patch

      - name: Apply lz4kd Patches
        run: |
          cd kernel_workspace/kernel_platform/common
          cp ../../SukiSU_patch/other/lz4k_patch/${{ github.event.inputs.KERNEL_VERSION }}/lz4kd.patch ./
          patch -p1 -F 3 < lz4kd.patch || true

      - name: Add SUSFS Configuration Settings
        run: |
          cd kernel_workspace/kernel_platform
          {
            echo "CONFIG_KSU=y";
            echo "CONFIG_KPM=y";
            echo "CONFIG_KSU_SUSFS_SUS_SU=n";
            echo "CONFIG_KSU_MANUAL_HOOK=y";
            echo "CONFIG_KSU_SUSFS=y";
            echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y";
            echo "CONFIG_KSU_SUSFS_SUS_PATH=y";
            echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y";
            echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y";
            echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y";
            echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y";
            echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=n";
            echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y";
            echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y";
            echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y";
            echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y";
            echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y";
            echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y";
            echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y";
            echo "CONFIG_CRYPTO_LZ4HC=y";
            echo "CONFIG_CRYPTO_LZ4K=y";
            echo "CONFIG_CRYPTO_LZ4KD=y";
            echo "CONFIG_CRYPTO_842=y";
          } >> ./common/arch/arm64/configs/gki_defconfig
          sed -i 's/check_defconfig//' ./common/build.config.gki
          cd common
          git add -A && git commit -a -m "BUILD: Apply kernel configs"

      - name: Add make name
        run: |
          cd kernel_workspace/kernel_platform
          sed -i 's/res="\$res\$(cat "\$file")"/res="${{ github.event.inputs.KERNEL_NAME }}"/g' ./common/scripts/setlocalversion

      - name: Configure sched_ext Driver
        run: |
          cd kernel_workspace/kernel_platform/common/kernel/sched
          if [[ ! -f "slim_sysctl.c" ]]; then
              tmp_dir=$(mktemp -d)
              echo "正在克隆私有仓库..."
              GIT_SSH_COMMAND="ssh -v" git clone git@github.com:MAXCUK/sched.git "$tmp_dir"
              find "$tmp_dir" -name "*.c" -exec cp -v {} . \;
              rm -rf "$tmp_dir"
          fi

      - name: Build kernel
        run: |
          cd kernel_workspace/kernel_platform
          tools/bazel run \
            --config=fast \
            --config=stamp \
            --lto=thin \
            //common:kernel_aarch64_dist \
            -- \
            --dist_dir=dist

      - name: Generate Kernel Images
        run: |
          cd kernel_workspace/kernel_platform/dist
          cp Image Image_original
          curl -fL -o patch_linux \
            https://github.com/ShirkNeko/SukiSU_KernelPatch_patch/releases/download/0.11-beta/patch_linux
          chmod +x patch_linux
          ./patch_linux
          mv oImage Image_kpm
          mv Image_original Image

      - name: Prepare AnyKernel3 Packages
        run: |
          cd kernel_workspace/kernel_platform/dist
          git clone git@github.com:MAXCUK/AnyKernel3-ace5Pro.git AnyKernel3-no_kpm --depth=1
          git clone git@github.com:MAXCUK/AnyKernel3-ace5Pro.git AnyKernel3-kpm --depth=1
          rm -rf AnyKernel3-{kpm,no_kpm}/.git
          find AnyKernel3-{kpm,no_kpm} -name "push.sh" -delete

      - name: 复制镜像文件
        run: |
          cd kernel_workspace/kernel_platform/dist
          cp -v Image AnyKernel3-no_kpm/
          cp -v Image_kpm AnyKernel3-kpm/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel_${{ env.KSUVER }}
          path: |
            kernel_workspace/kernel_platform/dist/AnyKernel3-*
