name: GKI Kernel Builder Pro

on:
  workflow_dispatch:
    inputs:
      CPU:
        description: "SoC平台分支 (e.g. sm8750)"
        required: true
        default: 'sm8750'
      FEIL:
        description: "设备配置文件 (e.g. oneplus_13t)"
        required: true
        default: 'oneplus_13t'
      ANDROID_VERSION:
        description: "安卓版本 (e.g. android15)"
        required: true
        default: 'android15'
      KERNEL_VERSION:
        description: "内核版本 (e.g. 6.6)"
        required: true
        default: '6.6'
      KERNEL_NAME:
        description: "自定义内核标识"
        required: true
        default: '-Android15-8-@'

env:
  CCACHE_DIR: /github/workspace/.ccache
  SWAPFILE: /swapfile16g
  WORKSPACE: /github/workspace/kernel_workspace

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:
    - name: 初始化工作区
      uses: actions/checkout@v4
      with:
        path: ${{ env.WORKSPACE }}

    - name: 配置缓存
      uses: actions/cache@v3
      with:
        path: |
          ${{ env.CCACHE_DIR }}
          ${{ env.WORKSPACE }}/.repo
        key: ${{ runner.os }}-kernel-${{ inputs.CPU }}-${{ hashFiles('.github/workflows/**') }}

    - name: 系统优化配置
      run: |
        # 清理系统空间
        sudo swapoff -a || true
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/hostedtoolcache/CodeQL
        sudo apt-get clean
        
        # 创建16GB交换空间
        sudo fallocate -l 16G $SWAPFILE
        sudo chmod 600 $SWAPFILE
        sudo mkswap $SWAPFILE
        sudo swapon $SWAPFILE
        free -h

    - name: 安装编译依赖
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          repo python3-venv ccache build-essential flex bison \
          libssl-dev libelf-dev zlib1g-dev patchelf

    - name: 初始化代码仓库
      working-directory: ${{ env.WORKSPACE }}
      run: |
        repo init -u https://github.com/OnePlusOSS/kernel_manifest.git \
          -b refs/heads/oneplus/${{ inputs.CPU }} \
          -m ${{ inputs.FEIL }}.xml \
          --depth=1 \
          --repo-url=https://gerrit.googlesource.com/git-repo

    - name: 同步源代码
      working-directory: ${{ env.WORKSPACE }}
      run: |
        for i in {1..5}; do
          repo sync -c -j$(nproc) --force-sync --no-tags && break
          find .repo -name '*.lock' -delete
          sleep $((i * 20))
        done

    - name: 应用内核补丁
      working-directory: ${{ env.WORKSPACE }}
      run: |
        # 集成KernelSU
        cd kernel_platform
        curl -sSL "https://raw.githubusercontent.com/ShirkNeko/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-dev
        KSU_VERSION=$(($(git -C KernelSU rev-list --count main) + 10606))
        echo "KSU_VERSION=${KSU_VERSION}" >> $GITHUB_ENV

        # 应用SUSFS补丁
        git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-${{ inputs.ANDROID_VERSION }}-${{ inputs.KERNEL_VERSION }}
        cp -v susfs4ksu/kernel_patches/50_add_susfs_in_gki-*.patch common/
        rsync -a susfs4ksu/kernel_patches/{fs,include/linux}/* common/

        # 应用LZ4K补丁
        git clone https://github.com/ExmikoN/SukiSU_patch
        cp -r SukiSU_patch/other/lz4k/{include,lib,crypto}/* common/

    - name: 内核配置
      working-directory: ${{ env.WORKSPACE }}/kernel_platform
      run: |
        # 修改版本标识
        sed -i "s/res=\\\$res\\\$(cat \\\"\\\$file\\\")/res='${{ inputs.KERNEL_NAME }}'/" common/scripts/setlocalversion

        # 更新defconfig
        cat <<EOF >> common/arch/arm64/configs/gki_defconfig
        CONFIG_KSU=y
        CONFIG_KPM=y
        CONFIG_CRYPTO_LZ4K=y
        CONFIG_CRYPTO_LZ4KD=y
        EOF

    - name: 编译内核
      working-directory: ${{ env.WORKSPACE }}/kernel_platform
      env:
        CCACHE_DIR: ${{ env.CCACHE_DIR }}
      run: |
        export PATH="/usr/lib/ccache:$PATH"
        ccache -M 20G
        ccache -s

        tools/bazel run --config=fast --config=stamp --lto=thin \
          //common:kernel_aarch64_dist -- --dist_dir=dist

    - name: 打包镜像
      working-directory: ${{ env.WORKSPACE }}/kernel_platform/dist
      run: |
        # 生成KPM镜像
        curl -LO https://github.com/ShirkNeko/SukiSU_KernelPatch_patch/releases/download/0.11-beta/patch_linux
        chmod +x patch_linux
        ./patch_linux || cp Image Image_kpm

        # 创建刷机包
        git clone https://${{ secrets.GH_TOKEN }}@github.com/MAXCUK/AnyKernel3-ace5Pro.git
        cp Image* AnyKernel3-ace5Pro/
        cd AnyKernel3-ace5Pro
        zip -r9 ../SukiSU_${{ env.KSU_VERSION }}_${{ inputs.FEIL }}_$(date +%Y%m%d).zip *

    - name: 上传制品
      uses: actions/upload-artifact@v4
      with:
        name: Kernel-Build-${{ env.KSU_VERSION }}
        path: ${{ env.WORKSPACE }}/kernel_platform/dist/*.zip
        retention-days: 7

    - name: 清理工作区
      if: always()
      working-directory: ${{ env.WORKSPACE }}
      run: |
        sudo swapoff $SWAPFILE
        sudo rm -f $SWAPFILE
        rm -rf kernel_platform/{KernelSU,susfs4ksu,SukiSU_patch}
